// Latency comparison (starter)
// kernel bypass filter generated by KBF Studio (c++ mode)
// generated 2026-09-29 16:40
// tiles: 9   wires: 9
// 
//   Axon feed                data_stream    id stream
//   Network Card             nic            id nic
//   Kernel / CPU Path        kernel_path    id kernel
//   Kernel Bypass            kernel_bypass  id bypass
//   Memory Store             memory         id memory
//   Snippet Definer          snippet        id snippet
//   Timestamp                timestamp      id stamp
//   Processor                processor      id proc
//   Latency Meter            latency_meter  id meter
// 
//   Axon feed  -->  Network Card
//   Network Card  -->  Kernel / CPU Path
//   Network Card  -->  Kernel Bypass
//   Kernel / CPU Path  -->  Memory Store
//   Kernel Bypass  -->  Snippet Definer
//   Snippet Definer  -->  Timestamp
//   Timestamp  -->  Processor
//   Processor  -->  Latency Meter
//   Latency Meter  -->  Memory Store
//
// Build:  c++ -O2 -std=c++17 -o kbf_filter kbf_filter.cpp
// Run:    ./kbf_filter                     simulate with a virtual clock
//         sudo ./kbf_filter --live eth0    read real frames from a NIC (Linux)
//         ./kbf_filter --udp 5555          listen on a UDP port
//         ./kbf_filter --max-packets N --seconds S --json --out DIR
//
// Tile API (each tile lives in its own namespace; P is its settings):
//   int  process(Packet& pkt, Ctx& ctx)     return 1 = pass, 0 = drop
//   bool generate(Ctx& ctx, Packet& pkt)    simulation source: fill pkt, return true; false = finished
//   void setup(Ctx&) / finish(Ctx&)         optional, run once
//   ctx.now(pkt) ctx.delay(pkt,ns) ctx.log(s) ctx.report(name,json) ctx.request_stop() ctx.gauss(sd)
//   kbf_parse(pkt) kbf_pct(v,q) kbf_mean(v) kbf_put16/32/64 kbf_get16/32/64 kbf_path_name(p)
//
// True kernel bypass: replace kbf_live_open()/kbf_live_read() with your DPDK / AF_XDP / ef_vi receive loop.
#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-function"   // tiles need not use every helper
#endif
#include <algorithm>
#include <cerrno>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <csignal>
#include <fstream>
#include <map>
#include <random>
#include <sstream>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
#ifndef _WIN32
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <sys/uio.h>
#include <unistd.h>
#endif
#ifdef __linux__
#include <linux/if_packet.h>
#include <net/ethernet.h>
#include <net/if.h>
#ifndef SO_TIMESTAMPNS
#define SO_TIMESTAMPNS 35
#endif
#endif

static const int KBF_MAX_FRAME = 2048;
enum class Path : uint8_t { Wire = 0, Kernel = 1, Bypass = 2 };
static const char* kbf_path_name(Path p) { return p == Path::Kernel ? "kernel" : p == Path::Bypass ? "bypass" : "wire"; }

struct Packet {
    uint32_t seq = 0;
    std::vector<uint8_t> data;
    bool has_eth = true;                         // data starts with an Ethernet header
    Path path = Path::Wire;
    int64_t t = 0;                               // position on the (virtual) clock, ns
    int64_t t_nic = -1;                          // when the card saw it, ns; -1 = not yet
    std::vector<std::pair<std::string, int64_t>> marks;
    std::unordered_map<std::string, double> meta;
    size_t len() const { return data.size(); }
    void reset(uint32_t s, int64_t time) { seq = s; t = time; t_nic = -1; path = Path::Wire; has_eth = true; marks.clear(); meta.clear(); }
};

struct Ctx {
    bool live = false, json = false, stop = false, ts_ok = false, live_has_eth = true;
    uint64_t packets_in = 0;
    std::string out_dir = ".";
    std::mt19937_64 rng{1};
    static int64_t wall_ns() { timespec ts; clock_gettime(CLOCK_REALTIME, &ts); return (int64_t)ts.tv_sec * 1000000000LL + ts.tv_nsec; }
    int64_t now(const Packet& p) const { return live ? wall_ns() : p.t; }
    void delay(Packet& p, int64_t ns) const { if (!live) const_cast<Packet&>(p).t += ns; }
    void request_stop() { stop = true; }
    double gauss(double sd) { std::normal_distribution<double> d(0.0, sd); return d(rng); }
    static std::string js(const std::string& s) { std::string o = "\""; for (char c : s) { if (c == '"' || c == '\\') o += '\\'; if (c == '\n') { o += "\\n"; continue; } o += c; } return o + "\""; }
    void log(const std::string& msg) { if (json) printf("{\"type\":\"log\",\"msg\":%s}\n", js(msg).c_str()); else puts(msg.c_str()); fflush(stdout); }
    void report(const std::string& name, const std::string& data) {
        if (json) printf("{\"type\":\"report\",\"name\":%s,\"data\":%s}\n", js(name).c_str(), data.c_str());
        else printf("\n=== %s ===\n%s\n\n", name.c_str(), data.c_str());
        fflush(stdout);
    }
};

struct Headers { int eth_type = -1, ip_proto = 0, sport = -1, dport = -1, payload_off = 0; uint32_t src_ip = 0, dst_ip = 0; };

static void kbf_put16(uint8_t* d, uint16_t v) { d[0] = (uint8_t)(v >> 8); d[1] = (uint8_t)v; }
static void kbf_put32(uint8_t* d, uint32_t v) { for (int i = 0; i < 4; i++) d[i] = (uint8_t)(v >> (24 - 8 * i)); }
static void kbf_put64(uint8_t* d, uint64_t v) { for (int i = 0; i < 8; i++) d[i] = (uint8_t)(v >> (56 - 8 * i)); }
static uint16_t kbf_get16(const uint8_t* d) { return (uint16_t)((d[0] << 8) | d[1]); }
static uint32_t kbf_get32(const uint8_t* d) { return ((uint32_t)d[0] << 24) | ((uint32_t)d[1] << 16) | ((uint32_t)d[2] << 8) | d[3]; }
static uint64_t kbf_get64(const uint8_t* d) { return ((uint64_t)kbf_get32(d) << 32) | kbf_get32(d + 4); }
static int64_t kbf_pct(std::vector<int64_t> v, double q) { if (v.empty()) return 0; std::sort(v.begin(), v.end()); size_t i = (size_t)(v.size() * q); if (i >= v.size()) i = v.size() - 1; return v[i]; }
static double kbf_mean(const std::vector<int64_t>& v) { double s = 0; for (auto x : v) s += (double)x; return v.empty() ? 0 : s / (double)v.size(); }

static Headers kbf_parse(const Packet& p) {                   // Ethernet(+VLAN)/IPv4/UDP|TCP
    Headers h; const uint8_t* d = p.data.data(); int off = 0, n = (int)p.data.size();
    if (p.has_eth) {
        if (n < 14) return h;
        h.eth_type = kbf_get16(d + 12); off = 14;
        if (h.eth_type == 0x8100 && n >= 18) { h.eth_type = kbf_get16(d + 16); off = 18; }
        if (h.eth_type != 0x0800) { h.payload_off = off; return h; }
    }
    if (n < off + 20 || (d[off] >> 4) != 4) { h.payload_off = off; return h; }
    int ihl = (d[off] & 0x0F) * 4;
    h.ip_proto = d[off + 9]; h.src_ip = kbf_get32(d + off + 12); h.dst_ip = kbf_get32(d + off + 16);
    off += ihl;
    if ((h.ip_proto == 6 || h.ip_proto == 17) && n >= off + 4) {
        h.sport = kbf_get16(d + off); h.dport = kbf_get16(d + off + 2);
        off += h.ip_proto == 17 ? 8 : (n >= off + 13 ? (d[off + 12] >> 4) * 4 : 20);
    }
    h.payload_off = std::min(off, n);
    return h;
}

// ---------------------------------------------------------------- live capture (the bypass hook)
#ifdef __linux__
static int kbf_live_open(Ctx& ctx, const char* iface, int udp_port) {
    int fd;
    if (iface) {
        fd = socket(AF_PACKET, SOCK_RAW, htons(ETH_P_ALL));
        if (fd < 0) { perror("socket(AF_PACKET): need root or CAP_NET_RAW"); return -1; }
        sockaddr_ll sll{}; sll.sll_family = AF_PACKET; sll.sll_protocol = htons(ETH_P_ALL); sll.sll_ifindex = (int)if_nametoindex(iface);
        if (!sll.sll_ifindex) { fprintf(stderr, "unknown interface %s\n", iface); return -1; }
        if (bind(fd, (sockaddr*)&sll, sizeof sll) < 0) { perror("bind"); return -1; }
        ctx.live_has_eth = true;
    } else {
        fd = socket(AF_INET, SOCK_DGRAM, 0);
        int one = 1; setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof one);
        sockaddr_in sa{}; sa.sin_family = AF_INET; sa.sin_port = htons((uint16_t)udp_port); sa.sin_addr.s_addr = INADDR_ANY;
        if (bind(fd, (sockaddr*)&sa, sizeof sa) < 0) { perror("bind"); return -1; }
        ctx.live_has_eth = false;
    }
    int one = 1; ctx.ts_ok = setsockopt(fd, SOL_SOCKET, SO_TIMESTAMPNS, &one, sizeof one) == 0;
    timeval tv{0, 500000}; setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof tv);
    ctx.log(std::string("live: listening on ") + (iface ? std::string("interface ") + iface : "udp port " + std::to_string(udp_port)) + " (kernel timestamps " + (ctx.ts_ok ? "on" : "off") + ")");
    return fd;
}
static int kbf_live_read(Ctx& ctx, int fd, Packet& pkt, uint32_t seq) {     // 1 packet, 0 timeout, -1 error
    static uint8_t buf[KBF_MAX_FRAME]; iovec iov{buf, sizeof buf}; char cbuf[256];
    msghdr msg{}; msg.msg_iov = &iov; msg.msg_iovlen = 1; msg.msg_control = cbuf; msg.msg_controllen = sizeof cbuf;
    ssize_t n = recvmsg(fd, &msg, 0);
    if (n < 0) { if (errno == EAGAIN || errno == EWOULDBLOCK || errno == EINTR) return 0; perror("recvmsg"); return -1; }
    int64_t now = Ctx::wall_ns(), t_nic = now;
    for (cmsghdr* c = CMSG_FIRSTHDR(&msg); c; c = CMSG_NXTHDR(&msg, c))
        if (c->cmsg_level == SOL_SOCKET && c->cmsg_type == SO_TIMESTAMPNS) { timespec ts; memcpy(&ts, CMSG_DATA(c), sizeof ts); t_nic = (int64_t)ts.tv_sec * 1000000000LL + ts.tv_nsec; }
    pkt.reset(seq, now); pkt.data.assign(buf, buf + n); pkt.t_nic = t_nic; pkt.has_eth = ctx.live_has_eth;
    return 1;
}
#else
static int kbf_live_open(Ctx&, const char*, int) { fprintf(stderr, "live capture is implemented for Linux in this build\n"); return -1; }
static int kbf_live_read(Ctx&, int, Packet&, uint32_t) { return -1; }
#endif

// ====================================================================== tiles
// ====== Tile: Axon feed (data_stream)  id stream ======
namespace tile_stream {
struct Params { double rate_bps; long long packet_bytes; const char* protocol; long long dst_port; double jitter_pct; long long burst_len; long long count; long long seed; };
static const Params P{ 2660000.0, 256LL, "axon", 5555LL, 5.0, 1LL, 5000LL, 1LL };
// DATA STREAM: stands in for bytes on the wire. generate() fills pkt, advances
// the virtual clock (pkt.t, ns) and returns true, or returns false when finished.
// Available: P (settings), kbf helpers, Packet, Ctx. Namespace-local state is fine.
static uint64_t seq_ = 0; static double t_ = 0, gap_ = 0;

static void build_frame(Packet& pkt, uint32_t seq) {
    int size = (int)P.packet_bytes; if (size > KBF_MAX_FRAME) size = KBF_MAX_FRAME; if (size < 60) size = 60;
    pkt.data.assign(size, 0);
    uint8_t* d = pkt.data.data();
    static const uint8_t eth[14] = {0x02,'K','B','F',0,1, 0x02,'A','X','N',0,1, 0x08,0x00};
    memcpy(d, eth, 14);
    std::string proto = P.protocol;
    if (proto == "raw") {
        d[12] = 0x88; d[13] = 0xb5; memcpy(d + 14, "AXON", 4); kbf_put32(d + 18, seq); kbf_put64(d + 22, 0);
        for (int i = 30; i < size; i++) d[i] = (uint8_t)(seq + i);
        return;
    }
    int payload_len = size - 42;
    uint8_t* ip = d + 14;
    ip[0] = 0x45; kbf_put16(ip + 2, (uint16_t)(28 + payload_len)); kbf_put16(ip + 4, (uint16_t)seq);
    ip[6] = 0x40; ip[8] = 64; ip[9] = 17; ip[12] = 10; ip[15] = 2; ip[16] = 10; ip[19] = 1;
    uint8_t* udp = d + 34;
    kbf_put16(udp, (uint16_t)(40000 + seq % 100)); kbf_put16(udp + 2, (uint16_t)P.dst_port);
    kbf_put16(udp + 4, (uint16_t)(8 + payload_len)); kbf_put16(udp + 6, 0);
    uint8_t* pl = d + 42;
    for (int i = 0; i < payload_len; i++) pl[i] = (uint8_t)(seq * 7 + i);
    if (proto == "axon" && payload_len >= 16) { memcpy(pl, "AXON", 4); kbf_put32(pl + 4, seq); kbf_put64(pl + 8, 0); }
    if (proto == "itch" && payload_len >= 38) {   // ITCH-style Add Order
        memset(pl, 0, 38); kbf_put16(pl, 36); pl[2] = 'A'; kbf_put16(pl + 3, 1);
        kbf_put64(pl + 13, seq); pl[21] = 'B'; kbf_put32(pl + 22, 100); memcpy(pl + 26, "AXON    ", 8); kbf_put32(pl + 34, 1234500);
    }
}

bool generate(Ctx& ctx, Packet& pkt) {
    if (seq_ == 0) gap_ = 1e9 * P.packet_bytes * 8.0 / P.rate_bps;   // mean inter-arrival, ns
    if (seq_ >= (uint64_t)P.count) return false;
    int burst = P.burst_len > 1 ? (int)P.burst_len : 1;
    double gap_in = gap_ * 0.05, gap_between = gap_ * burst - gap_in * (burst - 1);
    double g = burst == 1 ? gap_ : ((seq_ % burst) ? gap_in : gap_between);
    if (P.jitter_pct > 0) g += ctx.gauss(g * P.jitter_pct / 100.0);
    if (g < 0) g = 0;
    t_ += g;
    pkt.reset((uint32_t)seq_, (int64_t)t_);
    build_frame(pkt, (uint32_t)seq_);
    seq_++;
    return true;
}
}  // namespace tile_stream

// ====== Tile: Network Card (nic)  id nic ======
namespace tile_nic {
struct Params { const char* interface; const char* capture; long long udp_port; long long ingress_ns; long long max_frame; };
static const Params P{ "eth0", "raw", 5555LL, 430LL, 2048LL };
// NETWORK CARD: bytes become a packet here. Sets pkt.t_nic, the reference time.
// Live capture (AF_PACKET + SO_TIMESTAMPNS) is provided by the runtime: see kbf_live_read().
// To use a true bypass library (DPDK, AF_XDP, ef_vi), replace kbf_live_read() in the runtime section.
int process(Packet& pkt, Ctx& ctx) {
    if (pkt.t_nic < 0) {                           // simulated frame: model the ingress
        ctx.delay(pkt, (int64_t)P.ingress_ns);
        pkt.t_nic = ctx.now(pkt);
    }
    return 1;
}
}  // namespace tile_nic

// ====== Tile: Kernel / CPU Path (kernel_path)  id kernel ======
namespace tile_kernel {
struct Params { long long irq_ns; long long stack_ns; long long syscall_copy_ns; double copy_ns_per_byte; long long jitter_ns; int apply_delay; };
static const Params P{ 1500LL, 1500LL, 5900LL, 0.25, 1080LL, 1 };
// KERNEL / CPU PATH: models the conventional network stack.
int process(Packet& pkt, Ctx& ctx) {
    double est = P.irq_ns + P.stack_ns + P.syscall_copy_ns + pkt.len() * P.copy_ns_per_byte
               + (P.jitter_ns > 0 ? ctx.gauss(P.jitter_ns) : 0.0);
    if (est < 0) est = 0;
    if (P.apply_delay) { ctx.delay(pkt, (int64_t)est); pkt.path = Path::Kernel; }
    else pkt.meta["kernel_est_ns"] = est;
    return 1;
}
}  // namespace tile_kernel

// ====== Tile: Kernel Bypass (kernel_bypass)  id bypass ======
namespace tile_bypass {
struct Params { long long dma_ns; long long poll_interval_ns; double copy_ns_per_byte; long long jitter_ns; long long ring_size; };
static const Params P{ 1590LL, 3920LL, 0.05, 50LL, 1024LL };
// KERNEL BYPASS: DMA into a user-space ring, picked up by a polling loop.
int process(Packet& pkt, Ctx& ctx) {
    double cost = P.dma_ns + P.poll_interval_ns / 2.0 + pkt.len() * P.copy_ns_per_byte
                + (P.jitter_ns > 0 ? ctx.gauss(P.jitter_ns) : 0.0);
    if (cost < 0) cost = 0;
    ctx.delay(pkt, (int64_t)cost);
    pkt.path = Path::Bypass;
    pkt.meta["ring_slot"] = (double)(pkt.seq % (uint32_t)P.ring_size);
    return 1;
}
}  // namespace tile_bypass

// ====== Tile: Memory Store (memory)  id memory ======
namespace tile_memory {
struct Params { long long capacity_kb; int wrap; int dump_to_file; const char* file_prefix; int keep_marks; };
static const Params P{ 2048LL, 0, 1, "kbf_snapshot", 1 };
// MEMORY STORE: the destination, and the report that proves the numbers.
struct Entry { uint32_t off, len, seq; int64_t t_nic, t_mem; Path path; std::vector<std::pair<std::string,int64_t>> marks; };
static std::vector<uint8_t> buf_; static size_t wp_ = 0; static std::vector<Entry> idx_;
static long long dropped_ = 0, bytes_ = 0; static std::map<std::string, std::vector<int64_t>> lat_;
static std::vector<int64_t> est_; static int64_t first_ = -1, last_ = 0;

void setup(Ctx& ctx) { (void)ctx; buf_.assign((size_t)P.capacity_kb * 1024, 0); }

int process(Packet& pkt, Ctx& ctx) {
    int64_t t_mem = ctx.now(pkt); size_t n = pkt.len();
    if (wp_ + n > buf_.size()) { if (!P.wrap) { dropped_++; return 0; } wp_ = 0; }
    memcpy(buf_.data() + wp_, pkt.data.data(), n);        // the copy into application memory
    Entry e{(uint32_t)wp_, (uint32_t)n, pkt.seq, pkt.t_nic, t_mem, pkt.path, {}};
    if (P.keep_marks) e.marks = pkt.marks;
    idx_.push_back(std::move(e)); wp_ += n; bytes_ += (long long)n;
    if (pkt.t_nic >= 0) lat_[kbf_path_name(pkt.path)].push_back(t_mem - pkt.t_nic);
    auto it = pkt.meta.find("kernel_est_ns"); if (it != pkt.meta.end()) est_.push_back((int64_t)it->second);
    if (first_ < 0) first_ = t_mem;
    last_ = t_mem;
    return 0;                                             // sink
}

static std::string pct_block(const std::vector<int64_t>& v) {
    std::ostringstream o; o << "{\"min\":" << kbf_pct(v, 0) << ",\"p50\":" << kbf_pct(v, .5) << ",\"p99\":" << kbf_pct(v, .99)
                            << ",\"max\":" << kbf_pct(v, 1) << ",\"mean\":" << kbf_mean(v) << "}"; return o.str(); }

void finish(Ctx& ctx) {
    std::ostringstream js;
    js << "{\"packets\":" << idx_.size() << ",\"bytes\":" << bytes_ << ",\"dropped_buffer_full\":" << dropped_ << ",\"by_path\":{";
    bool first = true;
    for (auto& kv : lat_) { js << (first ? "" : ",") << "\"" << kv.first << "\":{\"count\":" << kv.second.size() << ",\"latency_ns\":" << pct_block(kv.second) << "}"; first = false; }
    js << "}";
    if (!est_.empty()) js << ",\"kernel_estimate_ns\":" << pct_block(est_);
    const std::vector<int64_t>* k = lat_.count("kernel") ? &lat_["kernel"] : (est_.empty() ? nullptr : &est_);
    if (k && lat_.count("bypass")) {
        auto& b = lat_["bypass"];
        js << ",\"savings_ns\":{\"p50\":" << kbf_pct(*k, .5) - kbf_pct(b, .5) << ",\"p99\":" << kbf_pct(*k, .99) - kbf_pct(b, .99)
           << ",\"mean\":" << kbf_mean(*k) - kbf_mean(b) << "}";
    }
    if (first_ >= 0 && last_ > first_) js << ",\"span_ms\":" << (last_ - first_) / 1e6 << ",\"throughput_mbps\":" << bytes_ * 8.0 / ((last_ - first_) / 1e9) / 1e6;
    if (P.dump_to_file) {
        std::string base = std::string(ctx.out_dir) + "/" + P.file_prefix;
        { std::ofstream f(base + ".bin", std::ios::binary); f.write((const char*)buf_.data(), (std::streamsize)wp_); }
        { std::ofstream f(base + "_index.json"); f << "[";
          for (size_t i = 0; i < idx_.size(); i++) { auto& e = idx_[i];
            f << (i ? "," : "") << "{\"off\":" << e.off << ",\"len\":" << e.len << ",\"seq\":" << e.seq << ",\"t_nic\":" << e.t_nic
              << ",\"t_mem\":" << e.t_mem << ",\"path\":\"" << kbf_path_name(e.path) << "\"";
            if (!e.marks.empty()) { f << ",\"marks\":{"; for (size_t m = 0; m < e.marks.size(); m++) f << (m ? "," : "") << "\"" << e.marks[m].first << "\":" << e.marks[m].second; f << "}"; }
            f << "}"; }
          f << "]"; }
        js << ",\"files\":[\"" << base << ".bin\",\"" << base << "_index.json\"]";
    }
    js << "}";
    ctx.report("Memory Store", js.str());
}
}  // namespace tile_memory

// ====== Tile: Snippet Definer (snippet)  id snippet ======
namespace tile_snippet {
struct Params { long long offset; long long length; long long max_packets; long long max_bytes; int stop_run_when_full; };
static const Params P{ 0LL, 64LL, 2000LL, 0LL, 0 };
// SNIPPET DEFINER: how much data leaves the wire and heads for memory.
static long long packets_ = 0, bytes_ = 0; static bool announced_ = false;

int process(Packet& pkt, Ctx& ctx) {
    bool full = packets_ >= P.max_packets || (P.max_bytes && bytes_ >= P.max_bytes);
    if (full) {
        if (!announced_) {
            announced_ = true;
            ctx.log("snippet complete: " + std::to_string(packets_) + " packets, " + std::to_string(bytes_) + " bytes");
            if (P.stop_run_when_full) ctx.request_stop();
        }
        return 0;                                        // drop
    }
    size_t off = std::min<size_t>((size_t)P.offset, pkt.data.size());
    size_t n = pkt.data.size() - off; if (P.length > 0 && n > (size_t)P.length) n = (size_t)P.length;
    pkt.data = std::vector<uint8_t>(pkt.data.begin() + off, pkt.data.begin() + off + n);
    packets_++; bytes_ += (long long)n;
    return 1;
}
}  // namespace tile_snippet

// ====== Tile: Timestamp (timestamp)  id stamp ======
namespace tile_stamp {
struct Params { const char* name; int append_to_payload; };
static const Params P{ "after_snippet", 0 };
// TIMESTAMP: record where this packet is in time.
int process(Packet& pkt, Ctx& ctx) {
    int64_t t = ctx.now(pkt);
    pkt.marks.emplace_back(P.name, t);
    if (P.append_to_payload) { uint8_t b[8]; kbf_put64(b, (uint64_t)t); pkt.data.insert(pkt.data.end(), b, b + 8); }
    return 1;
}
}  // namespace tile_stamp

// ====== Tile: Processor (processor)  id proc ======
namespace tile_proc {
struct Params { int drop_non_udp; int log_gaps; };
static const Params P{ 0, 1 };
// PROCESSOR: parse, extract, detect. Edit freely; this is your filter's brain.
static long long last_seq_ = -1, gaps_ = 0;

int process(Packet& pkt, Ctx& ctx) {
    Headers h = kbf_parse(pkt);
    pkt.meta["dport"] = h.dport;
    if (P.drop_non_udp && h.ip_proto != 17) return 0;
    const uint8_t* body = pkt.data.data() + h.payload_off; long long blen = (long long)pkt.len() - h.payload_off;
    if (blen >= 8 && memcmp(body, "AXON", 4) == 0) {
        long long seq = kbf_get32(body + 4);
        pkt.meta["axon_seq"] = (double)seq;
        if (last_seq_ >= 0 && seq != last_seq_ + 1) {
            gaps_++;
            if (P.log_gaps) ctx.log("gap: expected " + std::to_string(last_seq_ + 1) + " got " + std::to_string(seq));
        }
        last_seq_ = seq;
    }
    return 1;
}

void finish(Ctx& ctx) { ctx.log("processor: " + std::to_string(gaps_) + " sequence gaps"); }
}  // namespace tile_proc

// ====== Tile: Latency Meter (latency_meter)  id meter ======
namespace tile_meter {
struct Params { const char* name; long long report_every; };
static const Params P{ "before_memory", 1000LL };
// LATENCY METER: how long has this packet been in flight since the card?
static std::vector<int64_t> samples_;

int process(Packet& pkt, Ctx& ctx) {
    int64_t t = ctx.now(pkt);
    pkt.marks.emplace_back(P.name, t);
    if (pkt.t_nic >= 0) {
        samples_.push_back(t - pkt.t_nic);
        if (samples_.size() % (size_t)P.report_every == 0) {
            std::vector<int64_t> w(samples_.end() - (size_t)P.report_every, samples_.end());
            ctx.log(std::string(P.name) + ": last " + std::to_string(w.size()) + " pkts  p50 " +
                    std::to_string(kbf_pct(w, 0.5)) + " ns  p99 " + std::to_string(kbf_pct(w, 0.99)) + " ns");
        }
    }
    return 1;
}

void finish(Ctx& ctx) {
    if (samples_.empty()) return;
    std::ostringstream js;
    js << "{\"samples\":" << samples_.size() << ",\"min_ns\":" << kbf_pct(samples_, 0.0)
       << ",\"p50_ns\":" << kbf_pct(samples_, 0.5) << ",\"p99_ns\":" << kbf_pct(samples_, 0.99)
       << ",\"max_ns\":" << kbf_pct(samples_, 1.0) << "}";
    ctx.report(std::string("Latency meter '") + P.name + "'", js.str());
}
}  // namespace tile_meter

// ====== Pipeline ======
static void deliver_stream(Ctx& ctx, Packet& pkt);
static void deliver_nic(Ctx& ctx, Packet& pkt);
static void deliver_kernel(Ctx& ctx, Packet& pkt);
static void deliver_bypass(Ctx& ctx, Packet& pkt);
static void deliver_memory(Ctx& ctx, Packet& pkt);
static void deliver_snippet(Ctx& ctx, Packet& pkt);
static void deliver_stamp(Ctx& ctx, Packet& pkt);
static void deliver_proc(Ctx& ctx, Packet& pkt);
static void deliver_meter(Ctx& ctx, Packet& pkt);
static void deliver_stream(Ctx& ctx, Packet& pkt) {
    deliver_nic(ctx, pkt);
}
static void deliver_nic(Ctx& ctx, Packet& pkt) {
    if (!tile_nic::process(pkt, ctx)) return;
    { Packet copy = pkt; deliver_kernel(ctx, copy); }
    deliver_bypass(ctx, pkt);
}
static void deliver_kernel(Ctx& ctx, Packet& pkt) {
    if (!tile_kernel::process(pkt, ctx)) return;
    deliver_memory(ctx, pkt);
}
static void deliver_bypass(Ctx& ctx, Packet& pkt) {
    if (!tile_bypass::process(pkt, ctx)) return;
    deliver_snippet(ctx, pkt);
}
static void deliver_memory(Ctx& ctx, Packet& pkt) {
    if (!tile_memory::process(pkt, ctx)) return;
    (void)ctx; (void)pkt;
}
static void deliver_snippet(Ctx& ctx, Packet& pkt) {
    if (!tile_snippet::process(pkt, ctx)) return;
    deliver_stamp(ctx, pkt);
}
static void deliver_stamp(Ctx& ctx, Packet& pkt) {
    if (!tile_stamp::process(pkt, ctx)) return;
    deliver_proc(ctx, pkt);
}
static void deliver_proc(Ctx& ctx, Packet& pkt) {
    if (!tile_proc::process(pkt, ctx)) return;
    deliver_meter(ctx, pkt);
}
static void deliver_meter(Ctx& ctx, Packet& pkt) {
    if (!tile_meter::process(pkt, ctx)) return;
    deliver_memory(ctx, pkt);
}
static void kbf_setup_all(Ctx& ctx) { tile_memory::setup(ctx); }
static void kbf_finish_all(Ctx& ctx) { tile_memory::finish(ctx); tile_proc::finish(ctx); tile_meter::finish(ctx); }
static bool kbf_sim_next(Ctx& ctx, Packet& pkt) { return tile_stream::generate(ctx, pkt); }
static void kbf_sim_entry(Ctx& ctx, Packet& pkt) { deliver_stream(ctx, pkt); }
static void kbf_live_entry(Ctx& ctx, Packet& pkt) { deliver_nic(ctx, pkt); }
#define KBF_NAME "Latency comparison (starter)"
#define KBF_N_TILES 9
#define KBF_N_WIRES 9



// ====================================================================== main
static volatile std::sig_atomic_t kbf_signalled = 0;     // Ctrl-C / Stop button: finish cleanly, still report
static void kbf_on_signal(int) { kbf_signalled = 1; }

int main(int argc, char** argv) {
    std::signal(SIGINT, kbf_on_signal); std::signal(SIGTERM, kbf_on_signal);
    Ctx ctx; const char* iface = nullptr; int udp_port = 0; long long max_packets = 0; double seconds = 0;
    for (int i = 1; i < argc; i++) {
        std::string a = argv[i];
        if (a == "--live" && i + 1 < argc) iface = argv[++i];
        else if (a == "--udp" && i + 1 < argc) udp_port = atoi(argv[++i]);
        else if (a == "--max-packets" && i + 1 < argc) max_packets = atoll(argv[++i]);
        else if (a == "--seconds" && i + 1 < argc) seconds = atof(argv[++i]);
        else if (a == "--out" && i + 1 < argc) ctx.out_dir = argv[++i];
        else if (a == "--json") ctx.json = true;
        else { printf("usage: %s [--live IFACE | --udp PORT] [--max-packets N] [--seconds S] [--json] [--out DIR]\n", argv[0]); return a != "--help"; }
    }
    ctx.live = iface || udp_port;
    ctx.log(std::string(KBF_NAME) + ": " + (ctx.live ? "live" : "sim") + " mode, " + std::to_string(KBF_N_TILES) + " tiles, " + std::to_string(KBF_N_WIRES) + " wires");
    kbf_setup_all(ctx);
    Packet pkt; pkt.data.reserve(KBF_MAX_FRAME);
    long long n = 0; int64_t t_start = Ctx::wall_ns();
    if (ctx.live) {
        int fd = kbf_live_open(ctx, iface, udp_port); if (fd < 0) return 1;
        while (!ctx.stop && !kbf_signalled && (max_packets == 0 || n < max_packets)) {
            if (seconds > 0 && (double)(Ctx::wall_ns() - t_start) > seconds * 1e9) break;
            int r = kbf_live_read(ctx, fd, pkt, (uint32_t)n); if (r < 0) break; if (r == 0) continue;
            ctx.packets_in++; kbf_live_entry(ctx, pkt); n++;
            if (ctx.json && n % 1000 == 0) { printf("{\"type\":\"progress\",\"packets\":%lld}\n", n); fflush(stdout); }
        }
        close(fd);
    } else {
        while (!ctx.stop && !kbf_signalled && (max_packets == 0 || n < max_packets)) {
            if (!kbf_sim_next(ctx, pkt)) break;
            ctx.packets_in++; kbf_sim_entry(ctx, pkt); n++;
            if (ctx.json && n % 1000 == 0) { printf("{\"type\":\"progress\",\"packets\":%lld}\n", n); fflush(stdout); }
        }
    }
    kbf_finish_all(ctx);
    double wall_ms = (double)(Ctx::wall_ns() - t_start) / 1e6;
    if (ctx.json) printf("{\"type\":\"done\",\"packets\":%lld,\"wall_ms\":%.1f}\n", n, wall_ms);
    else printf("done: %lld packets in %.1f ms\n", n, wall_ms);
    return 0;
}
